### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by crystalfp** [erikdesjardins/eslint-plugin-no-useless-assign#9]
Inside VScode (latest).
During development I had a useless assign till I finished writing the correct statement. But eslint complained:
```
[Error - 2:30:26 PM] TypeError: Cannot read property 'id' of undefined
Occurred while linting D:\Projects\CouchDB\cli\parse.ts:316
    at checkForRedundantVar (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:54:15)
    at checkReturnStatement (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:101:4)
    at listeners.(anonymous function).forEach.listener (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Projects\CouchDB\node_modules\eslint\lib\linter\linter.js:885:32)
[Error - 2:30:27 PM] ESLint stack trace:
[Error - 2:30:27 PM] TypeError: Cannot read property 'id' of undefined
Occurred while linting D:\Projects\CouchDB\cli\parse.ts:316
    at checkForRedundantVar (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:54:15)
    at checkReturnStatement (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:101:4)
    at listeners.(anonymous function).forEach.listener (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Projects\CouchDB\node_modules\eslint\lib\linter\linter.js:885:32)
[Error - 2:30:29 PM] ESLint stack trace:
[Error - 2:30:29 PM] TypeError: Cannot read property 'id' of undefined
Occurred while linting D:\Projects\CouchDB\cli\parse.ts:316
    at checkForRedundantVar (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:54:15)
    at checkReturnStatement (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:101:4)
    at listeners.(anonymous function).forEach.listener (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Projects\CouchDB\node_modules\eslint\lib\linter\linter.js:885:32)
[Error - 2:30:31 PM] ESLint stack trace:
[Error - 2:30:31 PM] TypeError: Cannot read property 'id' of undefined
Occurred while linting D:\Projects\CouchDB\cli\parse.ts:316
    at checkForRedundantVar (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:54:15)
    at checkReturnStatement (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:101:4)
    at listeners.(anonymous function).forEach.listener (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Projects\CouchDB\node_modules\eslint\lib\linter\linter.js:885:32)
[Error - 2:30:35 PM] ESLint stack trace:
[Error - 2:30:35 PM] TypeError: Cannot read property 'id' of undefined
Occurred while linting D:\Projects\CouchDB\cli\parse.ts:316
    at checkForRedundantVar (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:54:15)
    at checkReturnStatement (D:\Projects\CouchDB\node_modules\eslint-plugin-no-useless-assign\rules\no-useless-assign.js:101:4)
    at listeners.(anonymous function).forEach.listener (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Projects\CouchDB\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Projects\CouchDB\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Projects\CouchDB\node_modules\eslint\lib\linter\linter.js:885:32)
```

**Comment by erikdesjardins** [comment]
Should be fixed in 1.0.3
